export const WageGaugePics = [
  {
    image:
    "/static/images/wagegauge/landingscreen.png"
  },
  {
    image:
    "/static/images/wagegauge/dashboard.png"
  },
  {
    image:
    "/static/images/wagegauge/figure.png"
  },
  {
    image:
    "/static/images/wagegauge/forumpage.png"
  },
  {
    image:
    "/static/images/wagegauge/newtopic.png"
  },
];